//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cross.DataVault.ServiceAccess.AccountsCloudService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentityPacket", Namespace="http://schemas.datacontract.org/2004/07/Cross.DataVault.Contracts.Data")]
    [System.SerializableAttribute()]
    public partial class IdentityPacket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Content_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> ErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Process_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Content_ID {
            get {
                return this.Content_IDField;
            }
            set {
                if ((this.Content_IDField.Equals(value) != true)) {
                    this.Content_IDField = value;
                    this.RaisePropertyChanged("Content_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasError {
            get {
                return this.HasErrorField;
            }
            set {
                if ((this.HasErrorField.Equals(value) != true)) {
                    this.HasErrorField = value;
                    this.RaisePropertyChanged("HasError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Process_ID {
            get {
                return this.Process_IDField;
            }
            set {
                if ((this.Process_IDField.Equals(value) != true)) {
                    this.Process_IDField = value;
                    this.RaisePropertyChanged("Process_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/Cross.DataVault.Contracts.Data")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] AvatarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Display_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Avatar {
            get {
                return this.AvatarField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarField, value) != true)) {
                    this.AvatarField = value;
                    this.RaisePropertyChanged("Avatar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Display_Name {
            get {
                return this.Display_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Display_NameField, value) != true)) {
                    this.Display_NameField = value;
                    this.RaisePropertyChanged("Display_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Home {
            get {
                return this.HomeField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeField, value) != true)) {
                    this.HomeField = value;
                    this.RaisePropertyChanged("Home");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last_Name {
            get {
                return this.Last_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_NameField, value) != true)) {
                    this.Last_NameField = value;
                    this.RaisePropertyChanged("Last_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_ID {
            get {
                return this.User_IDField;
            }
            set {
                if ((this.User_IDField.Equals(value) != true)) {
                    this.User_IDField = value;
                    this.RaisePropertyChanged("User_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Work {
            get {
                return this.WorkField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkField, value) != true)) {
                    this.WorkField = value;
                    this.RaisePropertyChanged("Work");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountsCloudService.IAccountManagement")]
    public interface IAccountManagement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Generate_AccountForCredentials", ReplyAction="http://tempuri.org/IAccountManagement/Generate_AccountForCredentialsResponse")]
        Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Generate_AccountForCredentials(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Generate_AccountForCredentials", ReplyAction="http://tempuri.org/IAccountManagement/Generate_AccountForCredentialsResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Generate_AccountForCredentialsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Generate_AccountForEmail", ReplyAction="http://tempuri.org/IAccountManagement/Generate_AccountForEmailResponse")]
        Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Generate_AccountForEmail(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Generate_AccountForEmail", ReplyAction="http://tempuri.org/IAccountManagement/Generate_AccountForEmailResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Generate_AccountForEmailAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Generate_AccountForUser", ReplyAction="http://tempuri.org/IAccountManagement/Generate_AccountForUserResponse")]
        Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Generate_AccountForUser(Cross.DataVault.ServiceAccess.AccountsCloudService.Account obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Generate_AccountForUser", ReplyAction="http://tempuri.org/IAccountManagement/Generate_AccountForUserResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Generate_AccountForUserAsync(Cross.DataVault.ServiceAccess.AccountsCloudService.Account obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Generate_AccountsForUsers", ReplyAction="http://tempuri.org/IAccountManagement/Generate_AccountsForUsersResponse")]
        Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Generate_AccountsForUsers(System.Collections.Generic.List<Cross.DataVault.ServiceAccess.AccountsCloudService.Account> objs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Generate_AccountsForUsers", ReplyAction="http://tempuri.org/IAccountManagement/Generate_AccountsForUsersResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Generate_AccountsForUsersAsync(System.Collections.Generic.List<Cross.DataVault.ServiceAccess.AccountsCloudService.Account> objs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Delete_AccountForUserID", ReplyAction="http://tempuri.org/IAccountManagement/Delete_AccountForUserIDResponse")]
        Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Delete_AccountForUserID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Delete_AccountForUserID", ReplyAction="http://tempuri.org/IAccountManagement/Delete_AccountForUserIDResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Delete_AccountForUserIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Delete_AccountsForUserIDs", ReplyAction="http://tempuri.org/IAccountManagement/Delete_AccountsForUserIDsResponse")]
        Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Delete_AccountsForUserIDs(System.Collections.Generic.List<int> ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Delete_AccountsForUserIDs", ReplyAction="http://tempuri.org/IAccountManagement/Delete_AccountsForUserIDsResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Delete_AccountsForUserIDsAsync(System.Collections.Generic.List<int> ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Disable_AccountsForUserID", ReplyAction="http://tempuri.org/IAccountManagement/Disable_AccountsForUserIDResponse")]
        Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Disable_AccountsForUserID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Disable_AccountsForUserID", ReplyAction="http://tempuri.org/IAccountManagement/Disable_AccountsForUserIDResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Disable_AccountsForUserIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Disable_AccountsForUserIDs", ReplyAction="http://tempuri.org/IAccountManagement/Disable_AccountsForUserIDsResponse")]
        Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Disable_AccountsForUserIDs(System.Collections.Generic.List<int> ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Disable_AccountsForUserIDs", ReplyAction="http://tempuri.org/IAccountManagement/Disable_AccountsForUserIDsResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Disable_AccountsForUserIDsAsync(System.Collections.Generic.List<int> ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Change_PasswordForUserID", ReplyAction="http://tempuri.org/IAccountManagement/Change_PasswordForUserIDResponse")]
        Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Change_PasswordForUserID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Change_PasswordForUserID", ReplyAction="http://tempuri.org/IAccountManagement/Change_PasswordForUserIDResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Change_PasswordForUserIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Change_EmailForUserID", ReplyAction="http://tempuri.org/IAccountManagement/Change_EmailForUserIDResponse")]
        Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Change_EmailForUserID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Change_EmailForUserID", ReplyAction="http://tempuri.org/IAccountManagement/Change_EmailForUserIDResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Change_EmailForUserIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Change_UsernameForUserID", ReplyAction="http://tempuri.org/IAccountManagement/Change_UsernameForUserIDResponse")]
        Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Change_UsernameForUserID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Change_UsernameForUserID", ReplyAction="http://tempuri.org/IAccountManagement/Change_UsernameForUserIDResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Change_UsernameForUserIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Change_PasswordForUserIDs", ReplyAction="http://tempuri.org/IAccountManagement/Change_PasswordForUserIDsResponse")]
        Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Change_PasswordForUserIDs(System.Collections.Generic.List<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Change_PasswordForUserIDs", ReplyAction="http://tempuri.org/IAccountManagement/Change_PasswordForUserIDsResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Change_PasswordForUserIDsAsync(System.Collections.Generic.List<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Change_EmailForUserIDs", ReplyAction="http://tempuri.org/IAccountManagement/Change_EmailForUserIDsResponse")]
        Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Change_EmailForUserIDs(System.Collections.Generic.List<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Change_EmailForUserIDs", ReplyAction="http://tempuri.org/IAccountManagement/Change_EmailForUserIDsResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Change_EmailForUserIDsAsync(System.Collections.Generic.List<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Change_UsernameForUserIDs", ReplyAction="http://tempuri.org/IAccountManagement/Change_UsernameForUserIDsResponse")]
        Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Change_UsernameForUserIDs(System.Collections.Generic.List<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManagement/Change_UsernameForUserIDs", ReplyAction="http://tempuri.org/IAccountManagement/Change_UsernameForUserIDsResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Change_UsernameForUserIDsAsync(System.Collections.Generic.List<int> id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountManagementChannel : Cross.DataVault.ServiceAccess.AccountsCloudService.IAccountManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountManagementClient : System.ServiceModel.ClientBase<Cross.DataVault.ServiceAccess.AccountsCloudService.IAccountManagement>, Cross.DataVault.ServiceAccess.AccountsCloudService.IAccountManagement {
        
        public AccountManagementClient() {
        }
        
        public AccountManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Generate_AccountForCredentials(string username, string password) {
            return base.Channel.Generate_AccountForCredentials(username, password);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Generate_AccountForCredentialsAsync(string username, string password) {
            return base.Channel.Generate_AccountForCredentialsAsync(username, password);
        }
        
        public Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Generate_AccountForEmail(string email, string password) {
            return base.Channel.Generate_AccountForEmail(email, password);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Generate_AccountForEmailAsync(string email, string password) {
            return base.Channel.Generate_AccountForEmailAsync(email, password);
        }
        
        public Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Generate_AccountForUser(Cross.DataVault.ServiceAccess.AccountsCloudService.Account obj) {
            return base.Channel.Generate_AccountForUser(obj);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Generate_AccountForUserAsync(Cross.DataVault.ServiceAccess.AccountsCloudService.Account obj) {
            return base.Channel.Generate_AccountForUserAsync(obj);
        }
        
        public Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Generate_AccountsForUsers(System.Collections.Generic.List<Cross.DataVault.ServiceAccess.AccountsCloudService.Account> objs) {
            return base.Channel.Generate_AccountsForUsers(objs);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Generate_AccountsForUsersAsync(System.Collections.Generic.List<Cross.DataVault.ServiceAccess.AccountsCloudService.Account> objs) {
            return base.Channel.Generate_AccountsForUsersAsync(objs);
        }
        
        public Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Delete_AccountForUserID(int id) {
            return base.Channel.Delete_AccountForUserID(id);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Delete_AccountForUserIDAsync(int id) {
            return base.Channel.Delete_AccountForUserIDAsync(id);
        }
        
        public Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Delete_AccountsForUserIDs(System.Collections.Generic.List<int> ids) {
            return base.Channel.Delete_AccountsForUserIDs(ids);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Delete_AccountsForUserIDsAsync(System.Collections.Generic.List<int> ids) {
            return base.Channel.Delete_AccountsForUserIDsAsync(ids);
        }
        
        public Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Disable_AccountsForUserID(int id) {
            return base.Channel.Disable_AccountsForUserID(id);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Disable_AccountsForUserIDAsync(int id) {
            return base.Channel.Disable_AccountsForUserIDAsync(id);
        }
        
        public Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Disable_AccountsForUserIDs(System.Collections.Generic.List<int> ids) {
            return base.Channel.Disable_AccountsForUserIDs(ids);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Disable_AccountsForUserIDsAsync(System.Collections.Generic.List<int> ids) {
            return base.Channel.Disable_AccountsForUserIDsAsync(ids);
        }
        
        public Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Change_PasswordForUserID(int id) {
            return base.Channel.Change_PasswordForUserID(id);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Change_PasswordForUserIDAsync(int id) {
            return base.Channel.Change_PasswordForUserIDAsync(id);
        }
        
        public Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Change_EmailForUserID(int id) {
            return base.Channel.Change_EmailForUserID(id);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Change_EmailForUserIDAsync(int id) {
            return base.Channel.Change_EmailForUserIDAsync(id);
        }
        
        public Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Change_UsernameForUserID(int id) {
            return base.Channel.Change_UsernameForUserID(id);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Change_UsernameForUserIDAsync(int id) {
            return base.Channel.Change_UsernameForUserIDAsync(id);
        }
        
        public Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Change_PasswordForUserIDs(System.Collections.Generic.List<int> id) {
            return base.Channel.Change_PasswordForUserIDs(id);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Change_PasswordForUserIDsAsync(System.Collections.Generic.List<int> id) {
            return base.Channel.Change_PasswordForUserIDsAsync(id);
        }
        
        public Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Change_EmailForUserIDs(System.Collections.Generic.List<int> id) {
            return base.Channel.Change_EmailForUserIDs(id);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Change_EmailForUserIDsAsync(System.Collections.Generic.List<int> id) {
            return base.Channel.Change_EmailForUserIDsAsync(id);
        }
        
        public Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket Change_UsernameForUserIDs(System.Collections.Generic.List<int> id) {
            return base.Channel.Change_UsernameForUserIDs(id);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.AccountsCloudService.IdentityPacket> Change_UsernameForUserIDsAsync(System.Collections.Generic.List<int> id) {
            return base.Channel.Change_UsernameForUserIDsAsync(id);
        }
    }
}
