//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cross.DataVault.ServiceAccess.DataVaultCloudService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notes", Namespace="http://schemas.datacontract.org/2004/07/Cross.DataVault.Contracts.Data")]
    [System.SerializableAttribute()]
    public partial class Notes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Note_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Time_OfCreationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Note_ID {
            get {
                return this.Note_IDField;
            }
            set {
                if ((this.Note_IDField.Equals(value) != true)) {
                    this.Note_IDField = value;
                    this.RaisePropertyChanged("Note_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time_OfCreation {
            get {
                return this.Time_OfCreationField;
            }
            set {
                if ((this.Time_OfCreationField.Equals(value) != true)) {
                    this.Time_OfCreationField = value;
                    this.RaisePropertyChanged("Time_OfCreation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_ID {
            get {
                return this.User_IDField;
            }
            set {
                if ((this.User_IDField.Equals(value) != true)) {
                    this.User_IDField = value;
                    this.RaisePropertyChanged("User_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentityPacket", Namespace="http://schemas.datacontract.org/2004/07/Cross.DataVault.Contracts.Data")]
    [System.SerializableAttribute()]
    public partial class IdentityPacket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Content_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> ErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Process_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Content_ID {
            get {
                return this.Content_IDField;
            }
            set {
                if ((this.Content_IDField.Equals(value) != true)) {
                    this.Content_IDField = value;
                    this.RaisePropertyChanged("Content_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasError {
            get {
                return this.HasErrorField;
            }
            set {
                if ((this.HasErrorField.Equals(value) != true)) {
                    this.HasErrorField = value;
                    this.RaisePropertyChanged("HasError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Process_ID {
            get {
                return this.Process_IDField;
            }
            set {
                if ((this.Process_IDField.Equals(value) != true)) {
                    this.Process_IDField = value;
                    this.RaisePropertyChanged("Process_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotesResponsePacket", Namespace="http://schemas.datacontract.org/2004/07/Cross.DataVault.Contracts.Data.Response")]
    [System.SerializableAttribute()]
    public partial class NotesResponsePacket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket ResponsePacketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cross.DataVault.ServiceAccess.DataVaultCloudService.Notes _NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Cross.DataVault.ServiceAccess.DataVaultCloudService.Notes> _NotesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket ResponsePacket {
            get {
                return this.ResponsePacketField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsePacketField, value) != true)) {
                    this.ResponsePacketField = value;
                    this.RaisePropertyChanged("ResponsePacket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.Notes _Note {
            get {
                return this._NoteField;
            }
            set {
                if ((object.ReferenceEquals(this._NoteField, value) != true)) {
                    this._NoteField = value;
                    this.RaisePropertyChanged("_Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Cross.DataVault.ServiceAccess.DataVaultCloudService.Notes> _Notes {
            get {
                return this._NotesField;
            }
            set {
                if ((object.ReferenceEquals(this._NotesField, value) != true)) {
                    this._NotesField = value;
                    this.RaisePropertyChanged("_Notes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Passwords", Namespace="http://schemas.datacontract.org/2004/07/Cross.DataVault.Contracts.Data")]
    [System.SerializableAttribute()]
    public partial class Passwords : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Password_DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Password_HashedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Password_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Time_OfCreationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password_Description {
            get {
                return this.Password_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.Password_DescriptionField, value) != true)) {
                    this.Password_DescriptionField = value;
                    this.RaisePropertyChanged("Password_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password_Hashed {
            get {
                return this.Password_HashedField;
            }
            set {
                if ((object.ReferenceEquals(this.Password_HashedField, value) != true)) {
                    this.Password_HashedField = value;
                    this.RaisePropertyChanged("Password_Hashed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Password_ID {
            get {
                return this.Password_IDField;
            }
            set {
                if ((this.Password_IDField.Equals(value) != true)) {
                    this.Password_IDField = value;
                    this.RaisePropertyChanged("Password_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time_OfCreation {
            get {
                return this.Time_OfCreationField;
            }
            set {
                if ((this.Time_OfCreationField.Equals(value) != true)) {
                    this.Time_OfCreationField = value;
                    this.RaisePropertyChanged("Time_OfCreation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_ID {
            get {
                return this.User_IDField;
            }
            set {
                if ((this.User_IDField.Equals(value) != true)) {
                    this.User_IDField = value;
                    this.RaisePropertyChanged("User_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordsResponsePacket", Namespace="http://schemas.datacontract.org/2004/07/Cross.DataVault.Contracts.Data.Response")]
    [System.SerializableAttribute()]
    public partial class PasswordsResponsePacket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket ResponsePacketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cross.DataVault.ServiceAccess.DataVaultCloudService.Passwords _PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Cross.DataVault.ServiceAccess.DataVaultCloudService.Passwords> _PasswordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket ResponsePacket {
            get {
                return this.ResponsePacketField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsePacketField, value) != true)) {
                    this.ResponsePacketField = value;
                    this.RaisePropertyChanged("ResponsePacket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.Passwords _Password {
            get {
                return this._PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this._PasswordField, value) != true)) {
                    this._PasswordField = value;
                    this.RaisePropertyChanged("_Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Cross.DataVault.ServiceAccess.DataVaultCloudService.Passwords> _Passwords {
            get {
                return this._PasswordsField;
            }
            set {
                if ((object.ReferenceEquals(this._PasswordsField, value) != true)) {
                    this._PasswordsField = value;
                    this.RaisePropertyChanged("_Passwords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/Cross.DataVault.Contracts.Data")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] AvatarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Display_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Avatar {
            get {
                return this.AvatarField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarField, value) != true)) {
                    this.AvatarField = value;
                    this.RaisePropertyChanged("Avatar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Display_Name {
            get {
                return this.Display_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Display_NameField, value) != true)) {
                    this.Display_NameField = value;
                    this.RaisePropertyChanged("Display_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Home {
            get {
                return this.HomeField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeField, value) != true)) {
                    this.HomeField = value;
                    this.RaisePropertyChanged("Home");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last_Name {
            get {
                return this.Last_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_NameField, value) != true)) {
                    this.Last_NameField = value;
                    this.RaisePropertyChanged("Last_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_ID {
            get {
                return this.User_IDField;
            }
            set {
                if ((this.User_IDField.Equals(value) != true)) {
                    this.User_IDField = value;
                    this.RaisePropertyChanged("User_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Work {
            get {
                return this.WorkField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkField, value) != true)) {
                    this.WorkField = value;
                    this.RaisePropertyChanged("Work");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountResponsePacket", Namespace="http://schemas.datacontract.org/2004/07/Cross.DataVault.Contracts.Data.Response")]
    [System.SerializableAttribute()]
    public partial class AccountResponsePacket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket ResponsePacketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cross.DataVault.ServiceAccess.DataVaultCloudService.Account _AccountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket ResponsePacket {
            get {
                return this.ResponsePacketField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsePacketField, value) != true)) {
                    this.ResponsePacketField = value;
                    this.RaisePropertyChanged("ResponsePacket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.Account _Account {
            get {
                return this._AccountField;
            }
            set {
                if ((object.ReferenceEquals(this._AccountField, value) != true)) {
                    this._AccountField = value;
                    this.RaisePropertyChanged("_Account");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contacts", Namespace="http://schemas.datacontract.org/2004/07/Cross.DataVault.Contracts.Data")]
    [System.SerializableAttribute()]
    public partial class Contacts : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Address_ID_RefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] AvatarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Contact_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalutationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiteUser_DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Address_ID_Ref {
            get {
                return this.Address_ID_RefField;
            }
            set {
                if ((this.Address_ID_RefField.Equals(value) != true)) {
                    this.Address_ID_RefField = value;
                    this.RaisePropertyChanged("Address_ID_Ref");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Avatar {
            get {
                return this.AvatarField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarField, value) != true)) {
                    this.AvatarField = value;
                    this.RaisePropertyChanged("Avatar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Contact_ID {
            get {
                return this.Contact_IDField;
            }
            set {
                if ((this.Contact_IDField.Equals(value) != true)) {
                    this.Contact_IDField = value;
                    this.RaisePropertyChanged("Contact_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Home {
            get {
                return this.HomeField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeField, value) != true)) {
                    this.HomeField = value;
                    this.RaisePropertyChanged("Home");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last_Name {
            get {
                return this.Last_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_NameField, value) != true)) {
                    this.Last_NameField = value;
                    this.RaisePropertyChanged("Last_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Salutation {
            get {
                return this.SalutationField;
            }
            set {
                if ((object.ReferenceEquals(this.SalutationField, value) != true)) {
                    this.SalutationField = value;
                    this.RaisePropertyChanged("Salutation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiteUser_DisplayName {
            get {
                return this.SiteUser_DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteUser_DisplayNameField, value) != true)) {
                    this.SiteUser_DisplayNameField = value;
                    this.RaisePropertyChanged("SiteUser_DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_ID {
            get {
                return this.User_IDField;
            }
            set {
                if ((this.User_IDField.Equals(value) != true)) {
                    this.User_IDField = value;
                    this.RaisePropertyChanged("User_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Work {
            get {
                return this.WorkField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkField, value) != true)) {
                    this.WorkField = value;
                    this.RaisePropertyChanged("Work");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactsResponsePacket", Namespace="http://schemas.datacontract.org/2004/07/Cross.DataVault.Contracts.Data.Response")]
    [System.SerializableAttribute()]
    public partial class ContactsResponsePacket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket ResponsePacketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cross.DataVault.ServiceAccess.DataVaultCloudService.Contacts _ContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Cross.DataVault.ServiceAccess.DataVaultCloudService.Contacts> _ContactsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket ResponsePacket {
            get {
                return this.ResponsePacketField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsePacketField, value) != true)) {
                    this.ResponsePacketField = value;
                    this.RaisePropertyChanged("ResponsePacket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.Contacts _Contact {
            get {
                return this._ContactField;
            }
            set {
                if ((object.ReferenceEquals(this._ContactField, value) != true)) {
                    this._ContactField = value;
                    this.RaisePropertyChanged("_Contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Cross.DataVault.ServiceAccess.DataVaultCloudService.Contacts> _Contacts {
            get {
                return this._ContactsField;
            }
            set {
                if ((object.ReferenceEquals(this._ContactsField, value) != true)) {
                    this._ContactsField = value;
                    this.RaisePropertyChanged("_Contacts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Music", Namespace="http://schemas.datacontract.org/2004/07/Cross.DataVault.Contracts.Data")]
    [System.SerializableAttribute()]
    public partial class Music : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_OfCreationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan LengthOfMusicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] Music_ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Music_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Music_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ReleaseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Artist {
            get {
                return this.ArtistField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistField, value) != true)) {
                    this.ArtistField = value;
                    this.RaisePropertyChanged("Artist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_OfCreation {
            get {
                return this.Date_OfCreationField;
            }
            set {
                if ((this.Date_OfCreationField.Equals(value) != true)) {
                    this.Date_OfCreationField = value;
                    this.RaisePropertyChanged("Date_OfCreation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan LengthOfMusic {
            get {
                return this.LengthOfMusicField;
            }
            set {
                if ((this.LengthOfMusicField.Equals(value) != true)) {
                    this.LengthOfMusicField = value;
                    this.RaisePropertyChanged("LengthOfMusic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Music_Content {
            get {
                return this.Music_ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.Music_ContentField, value) != true)) {
                    this.Music_ContentField = value;
                    this.RaisePropertyChanged("Music_Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Music_ID {
            get {
                return this.Music_IDField;
            }
            set {
                if ((this.Music_IDField.Equals(value) != true)) {
                    this.Music_IDField = value;
                    this.RaisePropertyChanged("Music_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Music_Name {
            get {
                return this.Music_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Music_NameField, value) != true)) {
                    this.Music_NameField = value;
                    this.RaisePropertyChanged("Music_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ReleaseDate {
            get {
                return this.ReleaseDateField;
            }
            set {
                if ((this.ReleaseDateField.Equals(value) != true)) {
                    this.ReleaseDateField = value;
                    this.RaisePropertyChanged("ReleaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_ID {
            get {
                return this.User_IDField;
            }
            set {
                if ((this.User_IDField.Equals(value) != true)) {
                    this.User_IDField = value;
                    this.RaisePropertyChanged("User_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MusicResponsePacket", Namespace="http://schemas.datacontract.org/2004/07/Cross.DataVault.Contracts.Data.Response")]
    [System.SerializableAttribute()]
    public partial class MusicResponsePacket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket ResponsePacketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cross.DataVault.ServiceAccess.DataVaultCloudService.Music _MusicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Cross.DataVault.ServiceAccess.DataVaultCloudService.Music> _MusicsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket ResponsePacket {
            get {
                return this.ResponsePacketField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsePacketField, value) != true)) {
                    this.ResponsePacketField = value;
                    this.RaisePropertyChanged("ResponsePacket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.Music _Music {
            get {
                return this._MusicField;
            }
            set {
                if ((object.ReferenceEquals(this._MusicField, value) != true)) {
                    this._MusicField = value;
                    this.RaisePropertyChanged("_Music");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Cross.DataVault.ServiceAccess.DataVaultCloudService.Music> _Musics {
            get {
                return this._MusicsField;
            }
            set {
                if ((object.ReferenceEquals(this._MusicsField, value) != true)) {
                    this._MusicsField = value;
                    this.RaisePropertyChanged("_Musics");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Photos", Namespace="http://schemas.datacontract.org/2004/07/Cross.DataVault.Contracts.Data")]
    [System.SerializableAttribute()]
    public partial class Photos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Photo_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Photo_MIMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Time_OfCreationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Photo_ID {
            get {
                return this.Photo_IDField;
            }
            set {
                if ((this.Photo_IDField.Equals(value) != true)) {
                    this.Photo_IDField = value;
                    this.RaisePropertyChanged("Photo_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Photo_MIME {
            get {
                return this.Photo_MIMEField;
            }
            set {
                if ((object.ReferenceEquals(this.Photo_MIMEField, value) != true)) {
                    this.Photo_MIMEField = value;
                    this.RaisePropertyChanged("Photo_MIME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time_OfCreation {
            get {
                return this.Time_OfCreationField;
            }
            set {
                if ((this.Time_OfCreationField.Equals(value) != true)) {
                    this.Time_OfCreationField = value;
                    this.RaisePropertyChanged("Time_OfCreation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_ID {
            get {
                return this.User_IDField;
            }
            set {
                if ((this.User_IDField.Equals(value) != true)) {
                    this.User_IDField = value;
                    this.RaisePropertyChanged("User_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhotosResponsePacket", Namespace="http://schemas.datacontract.org/2004/07/Cross.DataVault.Contracts.Data.Response")]
    [System.SerializableAttribute()]
    public partial class PhotosResponsePacket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket ResponsePacketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Cross.DataVault.ServiceAccess.DataVaultCloudService.Photos _PhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Cross.DataVault.ServiceAccess.DataVaultCloudService.Photos> _PhotosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket ResponsePacket {
            get {
                return this.ResponsePacketField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsePacketField, value) != true)) {
                    this.ResponsePacketField = value;
                    this.RaisePropertyChanged("ResponsePacket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.Photos _Photo {
            get {
                return this._PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this._PhotoField, value) != true)) {
                    this._PhotoField = value;
                    this.RaisePropertyChanged("_Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Cross.DataVault.ServiceAccess.DataVaultCloudService.Photos> _Photos {
            get {
                return this._PhotosField;
            }
            set {
                if ((object.ReferenceEquals(this._PhotosField, value) != true)) {
                    this._PhotosField = value;
                    this.RaisePropertyChanged("_Photos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataVaultCloudService.IDataVaultService")]
    public interface IDataVaultService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/IsServiceAvailable", ReplyAction="http://tempuri.org/IDataVaultService/IsServiceAvailableResponse")]
        bool IsServiceAvailable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/IsServiceAvailable", ReplyAction="http://tempuri.org/IDataVaultService/IsServiceAvailableResponse")]
        System.Threading.Tasks.Task<bool> IsServiceAvailableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/AddNote", ReplyAction="http://tempuri.org/IDataVaultService/AddNoteResponse")]
        Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket AddNote(Cross.DataVault.ServiceAccess.DataVaultCloudService.Notes note);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/AddNote", ReplyAction="http://tempuri.org/IDataVaultService/AddNoteResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket> AddNoteAsync(Cross.DataVault.ServiceAccess.DataVaultCloudService.Notes note);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/GetNote_ByID", ReplyAction="http://tempuri.org/IDataVaultService/GetNote_ByIDResponse")]
        Cross.DataVault.ServiceAccess.DataVaultCloudService.NotesResponsePacket GetNote_ByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/GetNote_ByID", ReplyAction="http://tempuri.org/IDataVaultService/GetNote_ByIDResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.NotesResponsePacket> GetNote_ByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/GetNotes_ByIDs", ReplyAction="http://tempuri.org/IDataVaultService/GetNotes_ByIDsResponse")]
        Cross.DataVault.ServiceAccess.DataVaultCloudService.NotesResponsePacket GetNotes_ByIDs(System.Collections.Generic.List<int> ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/GetNotes_ByIDs", ReplyAction="http://tempuri.org/IDataVaultService/GetNotes_ByIDsResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.NotesResponsePacket> GetNotes_ByIDsAsync(System.Collections.Generic.List<int> ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/GetNotes_ByUserID", ReplyAction="http://tempuri.org/IDataVaultService/GetNotes_ByUserIDResponse")]
        Cross.DataVault.ServiceAccess.DataVaultCloudService.NotesResponsePacket GetNotes_ByUserID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/GetNotes_ByUserID", ReplyAction="http://tempuri.org/IDataVaultService/GetNotes_ByUserIDResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.NotesResponsePacket> GetNotes_ByUserIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/AddPassword", ReplyAction="http://tempuri.org/IDataVaultService/AddPasswordResponse")]
        Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket AddPassword(Cross.DataVault.ServiceAccess.DataVaultCloudService.Passwords password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/AddPassword", ReplyAction="http://tempuri.org/IDataVaultService/AddPasswordResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket> AddPasswordAsync(Cross.DataVault.ServiceAccess.DataVaultCloudService.Passwords password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/GetPasswords_ByUserID", ReplyAction="http://tempuri.org/IDataVaultService/GetPasswords_ByUserIDResponse")]
        Cross.DataVault.ServiceAccess.DataVaultCloudService.PasswordsResponsePacket GetPasswords_ByUserID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/GetPasswords_ByUserID", ReplyAction="http://tempuri.org/IDataVaultService/GetPasswords_ByUserIDResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.PasswordsResponsePacket> GetPasswords_ByUserIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/GetPassword_ByID", ReplyAction="http://tempuri.org/IDataVaultService/GetPassword_ByIDResponse")]
        Cross.DataVault.ServiceAccess.DataVaultCloudService.PasswordsResponsePacket GetPassword_ByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/GetPassword_ByID", ReplyAction="http://tempuri.org/IDataVaultService/GetPassword_ByIDResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.PasswordsResponsePacket> GetPassword_ByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/GetPasswords_ByIDs", ReplyAction="http://tempuri.org/IDataVaultService/GetPasswords_ByIDsResponse")]
        Cross.DataVault.ServiceAccess.DataVaultCloudService.PasswordsResponsePacket GetPasswords_ByIDs(System.Collections.Generic.List<int> ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/GetPasswords_ByIDs", ReplyAction="http://tempuri.org/IDataVaultService/GetPasswords_ByIDsResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.PasswordsResponsePacket> GetPasswords_ByIDsAsync(System.Collections.Generic.List<int> ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/AddAccount", ReplyAction="http://tempuri.org/IDataVaultService/AddAccountResponse")]
        Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket AddAccount(Cross.DataVault.ServiceAccess.DataVaultCloudService.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/AddAccount", ReplyAction="http://tempuri.org/IDataVaultService/AddAccountResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket> AddAccountAsync(Cross.DataVault.ServiceAccess.DataVaultCloudService.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/Get_Account_ViaAuthentication", ReplyAction="http://tempuri.org/IDataVaultService/Get_Account_ViaAuthenticationResponse")]
        Cross.DataVault.ServiceAccess.DataVaultCloudService.AccountResponsePacket Get_Account_ViaAuthentication(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/Get_Account_ViaAuthentication", ReplyAction="http://tempuri.org/IDataVaultService/Get_Account_ViaAuthenticationResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.AccountResponsePacket> Get_Account_ViaAuthenticationAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/AddContact", ReplyAction="http://tempuri.org/IDataVaultService/AddContactResponse")]
        Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket AddContact(Cross.DataVault.ServiceAccess.DataVaultCloudService.Contacts contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/AddContact", ReplyAction="http://tempuri.org/IDataVaultService/AddContactResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket> AddContactAsync(Cross.DataVault.ServiceAccess.DataVaultCloudService.Contacts contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/Get_ContactByID", ReplyAction="http://tempuri.org/IDataVaultService/Get_ContactByIDResponse")]
        Cross.DataVault.ServiceAccess.DataVaultCloudService.ContactsResponsePacket Get_ContactByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/Get_ContactByID", ReplyAction="http://tempuri.org/IDataVaultService/Get_ContactByIDResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.ContactsResponsePacket> Get_ContactByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/Get_ContactsByUserID", ReplyAction="http://tempuri.org/IDataVaultService/Get_ContactsByUserIDResponse")]
        Cross.DataVault.ServiceAccess.DataVaultCloudService.ContactsResponsePacket Get_ContactsByUserID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/Get_ContactsByUserID", ReplyAction="http://tempuri.org/IDataVaultService/Get_ContactsByUserIDResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.ContactsResponsePacket> Get_ContactsByUserIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/Get_ContactsByIDs", ReplyAction="http://tempuri.org/IDataVaultService/Get_ContactsByIDsResponse")]
        Cross.DataVault.ServiceAccess.DataVaultCloudService.ContactsResponsePacket Get_ContactsByIDs(System.Collections.Generic.List<int> ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/Get_ContactsByIDs", ReplyAction="http://tempuri.org/IDataVaultService/Get_ContactsByIDsResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.ContactsResponsePacket> Get_ContactsByIDsAsync(System.Collections.Generic.List<int> ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/AddMusic", ReplyAction="http://tempuri.org/IDataVaultService/AddMusicResponse")]
        Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket AddMusic(Cross.DataVault.ServiceAccess.DataVaultCloudService.Music music);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/AddMusic", ReplyAction="http://tempuri.org/IDataVaultService/AddMusicResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket> AddMusicAsync(Cross.DataVault.ServiceAccess.DataVaultCloudService.Music music);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/Get_MusicByID", ReplyAction="http://tempuri.org/IDataVaultService/Get_MusicByIDResponse")]
        Cross.DataVault.ServiceAccess.DataVaultCloudService.MusicResponsePacket Get_MusicByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/Get_MusicByID", ReplyAction="http://tempuri.org/IDataVaultService/Get_MusicByIDResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.MusicResponsePacket> Get_MusicByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/Get_MusicByUserID", ReplyAction="http://tempuri.org/IDataVaultService/Get_MusicByUserIDResponse")]
        Cross.DataVault.ServiceAccess.DataVaultCloudService.MusicResponsePacket Get_MusicByUserID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/Get_MusicByUserID", ReplyAction="http://tempuri.org/IDataVaultService/Get_MusicByUserIDResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.MusicResponsePacket> Get_MusicByUserIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/Get_MusicByIDs", ReplyAction="http://tempuri.org/IDataVaultService/Get_MusicByIDsResponse")]
        Cross.DataVault.ServiceAccess.DataVaultCloudService.MusicResponsePacket Get_MusicByIDs(System.Collections.Generic.List<int> ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/Get_MusicByIDs", ReplyAction="http://tempuri.org/IDataVaultService/Get_MusicByIDsResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.MusicResponsePacket> Get_MusicByIDsAsync(System.Collections.Generic.List<int> ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/AddPhoto", ReplyAction="http://tempuri.org/IDataVaultService/AddPhotoResponse")]
        Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket AddPhoto(Cross.DataVault.ServiceAccess.DataVaultCloudService.Photos photo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/AddPhoto", ReplyAction="http://tempuri.org/IDataVaultService/AddPhotoResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket> AddPhotoAsync(Cross.DataVault.ServiceAccess.DataVaultCloudService.Photos photo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/Get_PhotoByID", ReplyAction="http://tempuri.org/IDataVaultService/Get_PhotoByIDResponse")]
        Cross.DataVault.ServiceAccess.DataVaultCloudService.PhotosResponsePacket Get_PhotoByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/Get_PhotoByID", ReplyAction="http://tempuri.org/IDataVaultService/Get_PhotoByIDResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.PhotosResponsePacket> Get_PhotoByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/Get_PhotoByUserID", ReplyAction="http://tempuri.org/IDataVaultService/Get_PhotoByUserIDResponse")]
        Cross.DataVault.ServiceAccess.DataVaultCloudService.PhotosResponsePacket Get_PhotoByUserID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/Get_PhotoByUserID", ReplyAction="http://tempuri.org/IDataVaultService/Get_PhotoByUserIDResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.PhotosResponsePacket> Get_PhotoByUserIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/Get_PhotoByIDs", ReplyAction="http://tempuri.org/IDataVaultService/Get_PhotoByIDsResponse")]
        Cross.DataVault.ServiceAccess.DataVaultCloudService.PhotosResponsePacket Get_PhotoByIDs(System.Collections.Generic.List<int> ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataVaultService/Get_PhotoByIDs", ReplyAction="http://tempuri.org/IDataVaultService/Get_PhotoByIDsResponse")]
        System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.PhotosResponsePacket> Get_PhotoByIDsAsync(System.Collections.Generic.List<int> ids);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataVaultServiceChannel : Cross.DataVault.ServiceAccess.DataVaultCloudService.IDataVaultService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataVaultServiceClient : System.ServiceModel.ClientBase<Cross.DataVault.ServiceAccess.DataVaultCloudService.IDataVaultService>, Cross.DataVault.ServiceAccess.DataVaultCloudService.IDataVaultService {
        
        public DataVaultServiceClient() {
        }
        
        public DataVaultServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataVaultServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataVaultServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataVaultServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsServiceAvailable() {
            return base.Channel.IsServiceAvailable();
        }
        
        public System.Threading.Tasks.Task<bool> IsServiceAvailableAsync() {
            return base.Channel.IsServiceAvailableAsync();
        }
        
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket AddNote(Cross.DataVault.ServiceAccess.DataVaultCloudService.Notes note) {
            return base.Channel.AddNote(note);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket> AddNoteAsync(Cross.DataVault.ServiceAccess.DataVaultCloudService.Notes note) {
            return base.Channel.AddNoteAsync(note);
        }
        
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.NotesResponsePacket GetNote_ByID(int id) {
            return base.Channel.GetNote_ByID(id);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.NotesResponsePacket> GetNote_ByIDAsync(int id) {
            return base.Channel.GetNote_ByIDAsync(id);
        }
        
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.NotesResponsePacket GetNotes_ByIDs(System.Collections.Generic.List<int> ids) {
            return base.Channel.GetNotes_ByIDs(ids);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.NotesResponsePacket> GetNotes_ByIDsAsync(System.Collections.Generic.List<int> ids) {
            return base.Channel.GetNotes_ByIDsAsync(ids);
        }
        
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.NotesResponsePacket GetNotes_ByUserID(int id) {
            return base.Channel.GetNotes_ByUserID(id);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.NotesResponsePacket> GetNotes_ByUserIDAsync(int id) {
            return base.Channel.GetNotes_ByUserIDAsync(id);
        }
        
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket AddPassword(Cross.DataVault.ServiceAccess.DataVaultCloudService.Passwords password) {
            return base.Channel.AddPassword(password);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket> AddPasswordAsync(Cross.DataVault.ServiceAccess.DataVaultCloudService.Passwords password) {
            return base.Channel.AddPasswordAsync(password);
        }
        
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.PasswordsResponsePacket GetPasswords_ByUserID(int id) {
            return base.Channel.GetPasswords_ByUserID(id);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.PasswordsResponsePacket> GetPasswords_ByUserIDAsync(int id) {
            return base.Channel.GetPasswords_ByUserIDAsync(id);
        }
        
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.PasswordsResponsePacket GetPassword_ByID(int id) {
            return base.Channel.GetPassword_ByID(id);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.PasswordsResponsePacket> GetPassword_ByIDAsync(int id) {
            return base.Channel.GetPassword_ByIDAsync(id);
        }
        
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.PasswordsResponsePacket GetPasswords_ByIDs(System.Collections.Generic.List<int> ids) {
            return base.Channel.GetPasswords_ByIDs(ids);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.PasswordsResponsePacket> GetPasswords_ByIDsAsync(System.Collections.Generic.List<int> ids) {
            return base.Channel.GetPasswords_ByIDsAsync(ids);
        }
        
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket AddAccount(Cross.DataVault.ServiceAccess.DataVaultCloudService.Account account) {
            return base.Channel.AddAccount(account);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket> AddAccountAsync(Cross.DataVault.ServiceAccess.DataVaultCloudService.Account account) {
            return base.Channel.AddAccountAsync(account);
        }
        
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.AccountResponsePacket Get_Account_ViaAuthentication(string username, string password) {
            return base.Channel.Get_Account_ViaAuthentication(username, password);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.AccountResponsePacket> Get_Account_ViaAuthenticationAsync(string username, string password) {
            return base.Channel.Get_Account_ViaAuthenticationAsync(username, password);
        }
        
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket AddContact(Cross.DataVault.ServiceAccess.DataVaultCloudService.Contacts contact) {
            return base.Channel.AddContact(contact);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket> AddContactAsync(Cross.DataVault.ServiceAccess.DataVaultCloudService.Contacts contact) {
            return base.Channel.AddContactAsync(contact);
        }
        
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.ContactsResponsePacket Get_ContactByID(int id) {
            return base.Channel.Get_ContactByID(id);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.ContactsResponsePacket> Get_ContactByIDAsync(int id) {
            return base.Channel.Get_ContactByIDAsync(id);
        }
        
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.ContactsResponsePacket Get_ContactsByUserID(int id) {
            return base.Channel.Get_ContactsByUserID(id);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.ContactsResponsePacket> Get_ContactsByUserIDAsync(int id) {
            return base.Channel.Get_ContactsByUserIDAsync(id);
        }
        
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.ContactsResponsePacket Get_ContactsByIDs(System.Collections.Generic.List<int> ids) {
            return base.Channel.Get_ContactsByIDs(ids);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.ContactsResponsePacket> Get_ContactsByIDsAsync(System.Collections.Generic.List<int> ids) {
            return base.Channel.Get_ContactsByIDsAsync(ids);
        }
        
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket AddMusic(Cross.DataVault.ServiceAccess.DataVaultCloudService.Music music) {
            return base.Channel.AddMusic(music);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket> AddMusicAsync(Cross.DataVault.ServiceAccess.DataVaultCloudService.Music music) {
            return base.Channel.AddMusicAsync(music);
        }
        
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.MusicResponsePacket Get_MusicByID(int id) {
            return base.Channel.Get_MusicByID(id);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.MusicResponsePacket> Get_MusicByIDAsync(int id) {
            return base.Channel.Get_MusicByIDAsync(id);
        }
        
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.MusicResponsePacket Get_MusicByUserID(int id) {
            return base.Channel.Get_MusicByUserID(id);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.MusicResponsePacket> Get_MusicByUserIDAsync(int id) {
            return base.Channel.Get_MusicByUserIDAsync(id);
        }
        
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.MusicResponsePacket Get_MusicByIDs(System.Collections.Generic.List<int> ids) {
            return base.Channel.Get_MusicByIDs(ids);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.MusicResponsePacket> Get_MusicByIDsAsync(System.Collections.Generic.List<int> ids) {
            return base.Channel.Get_MusicByIDsAsync(ids);
        }
        
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket AddPhoto(Cross.DataVault.ServiceAccess.DataVaultCloudService.Photos photo) {
            return base.Channel.AddPhoto(photo);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.IdentityPacket> AddPhotoAsync(Cross.DataVault.ServiceAccess.DataVaultCloudService.Photos photo) {
            return base.Channel.AddPhotoAsync(photo);
        }
        
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.PhotosResponsePacket Get_PhotoByID(int id) {
            return base.Channel.Get_PhotoByID(id);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.PhotosResponsePacket> Get_PhotoByIDAsync(int id) {
            return base.Channel.Get_PhotoByIDAsync(id);
        }
        
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.PhotosResponsePacket Get_PhotoByUserID(int id) {
            return base.Channel.Get_PhotoByUserID(id);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.PhotosResponsePacket> Get_PhotoByUserIDAsync(int id) {
            return base.Channel.Get_PhotoByUserIDAsync(id);
        }
        
        public Cross.DataVault.ServiceAccess.DataVaultCloudService.PhotosResponsePacket Get_PhotoByIDs(System.Collections.Generic.List<int> ids) {
            return base.Channel.Get_PhotoByIDs(ids);
        }
        
        public System.Threading.Tasks.Task<Cross.DataVault.ServiceAccess.DataVaultCloudService.PhotosResponsePacket> Get_PhotoByIDsAsync(System.Collections.Generic.List<int> ids) {
            return base.Channel.Get_PhotoByIDsAsync(ids);
        }
    }
}
